# 用于定义 group 和显示的工具

- # 组名
  title: 显示文本
  # 工具显示大小, 可选 large(默认), default, small
  toolSize: large
  # 工具列表
  tools:
    # 工具标题
    - title: xx工具xx工具xx工具xx工具xx工具xx工具xx工具
      # 工具图标url地址
      icon: /icons/tool.ico
      # 工具提示
      desc: 工具提示
      # 搜索关键词, 前缀匹配
      searchKeywords:
        - 百度
        - baidu
      # 跳转定义, 可选
      skips:
        # 在tags.yaml中定义的tagKey, * 表示任意
        - tagKey: '*'
          # 跳转地址
          skipUri: https://www.github.com
          # 跳转类型, _self 表示在当前页面打开(默认), _blank 表示在新的页面打开
          skipType: _blank

    - title: xx工具2
      icon: /icons/tool.ico

- title: 组2
  toolSize: default
  tools:
    - title: xx工具xx工具xx工具xx工具xx工具xx工具xx工具
      icon: /icons/tool.ico
      skips:
        - tagKey: domain
          skipUri: https://www.github.com
          skipType: _blank
        - tagKey: key2
          skipUri: https://www.baidu.com
          skipType: _blank

- title: 组3
  toolSize: small
  tools:
    - title: xx工具xx工具xx工具xx工具xx工具xx工具xx工具
      icon: /icons/tool.ico
      skips:
        - tagKey: domain
          skipUri: https://www.github.com
          skipType: _blank
    - title: xx工具
      icon: /icons/tool.ico

- title: 组4
  tools:
    - title: xx工具
      icon: /icons/tool.ico

    - title: xx工具
      skips:
        - tagKey: key2
          skipUri: https://www.github.com

- title: 组5
  tools:
    - title: xx工具
      icon: /icons/tool.ico

- title: 组6
  tools:
    - title: xx工具
      icon: /icons/tool.ico

- title: 组7
  tools:
    - title: xx工具
      icon: /icons/tool.ico
      skips:

- title: 组8
  tools:
    - title: xx工具
      icon: /icons/tool.ico