# 用于定义 group 和显示的工具

- # 组名
  title: 显示文本
  # 工具
  tools:
    # 工具标题
    - title: xx工具
      # 工具图标url地址
      icon: /icons/tool.ico
      # 跳转定义, 可选
      skips:
        # 在tags.yaml中定义的tagKey
        - tagKey: key1
          # 跳转地址
          skipUri: https://www.github.com
          # 跳转类型, _self 表示在当前页面打开, _blank 表示在新的页面打开
          skipType: _blank

    - title: xx工具2
      icon: /icons/tool.ico

- title: 组2
  tools:
    - title: xx工具
      icon: /icons/tool.ico
      skips:
        - tagKey: key1
          skipUri: https://www.github.com
          skipType: _blank
        - tagKey: key2
          skipUri: https://www.baidu.com
          skipType: _blank

- title: 组3
  tools:

- title: 组4
  tools:
    - title: xx工具
      icon: /icons/tool.ico

- title: 组5
  tools:
    - title: xx工具
      icon: /icons/tool.ico

- title: 组6
  tools:
    - title: xx工具
      icon: /icons/tool.ico

- title: 组7
  tools:
    - title: xx工具
      icon: /icons/tool.ico
      skips:

- title: 组8
  tools:
    - title: xx工具
      icon: /icons/tool.ico