# 用于定义一个链接

# 链接文本
- title: github.com
  # 链接描述
  desc: 链接描述
  # 跳转定义, 可选
  skips:
    # 在tags.yaml中定义的tagKey, * 表示任意
    - tagKey: '*'
      # 跳转地址
      skipUri: https://www.github.com
      # 跳转类型, _self 表示在当前页面打开(默认), _blank 表示在新的页面打开
      skipType: _blank

- title: baidu.com
  desc: 链接描述
  skips:
    - tagKey: domain
      skipUri: https://www.baidu.com

- title: invalid
