# 用于定义有哪些 tag 和 group
# tag 表示右上角能切换的选项
# group 表示页面上有哪些工具分类

# 标题
- title: 网站
  # 一个唯一标记, 用于确认跳转时选择哪个跳转项
  tagKey: domain
  # 当没有该类型的跳转时会屏蔽工具或组等
  #filterInvalid: false

- title: 跳转地址2
  tagKey: key2
  # 当工具不可用时, 过滤掉该工具和组
  filterInvalid: true

- title: 跳转地址3
  tagKey: key3
